### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by Alrauna** [Vibesfr/beammp-egg-pterodactyl#3]
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./BeamMP-Server
./BeamMP-Server: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by ./BeamMP-Server)
./BeamMP-Server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by ./BeamMP-Server)

**Comment by Vibesfr** [comment]
Hi can you check in the admin dashboard / egg if the image is ghcr.io/vibesfr/pterodactyl-beammp-egg:main
